[workspace]

members = [
    "whirlwing",
    "whirlwing-playground",

    "whirlwing/crates/wwg-window",
    "whirlwing/crates/wwg-window-internal",
    
    "whirlwing/crates/wwg-events",

    "whirlwing/crates/wwg-log",

    "whirlwing/crates/platform/wwg-win32",
]