[workspace]

members = [
    "whirlwing",
    "whirlwing-playground",

    "whirlwing/crates/wwg-window",
    "whirlwing/crates/platform/wwg-windows",
    "whirlwing/crates/wwg-events",
    "whirlwing/crates/wwg-log",
]