[package]
name = "wwg-window"
version = "0.1.0"
edition = "2021"

[dependencies]
wwg-window-internal = { path = "../wwg-window-internal" }

[target.'cfg(windows)'.dependencies]
wwg-win32 = { path = "../platform/wwg-win32" }